// <auto-generated /> This file was auto-generated during migration
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendorProject.EF.Data;

#nullable disable

namespace VendorProject.EF.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    [Migration("20260126000000_AddOtpAuthenticationModels")]
    partial class AddOtpAuthenticationModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // All entity configurations are applied via EntityConfigurations
#pragma warning restore 612, 618
        }
    }
}
